name: IndexNow Submit by Category

on:
  push:
    paths:
      - '_posts/**/*.md'

jobs:
  submit-to-indexnow:
    runs-on: ubuntu-latest

    steps:
    - name: 🔍 Checkout repository
      uses: actions/checkout@v3

    - name: 🚀 Kirim ke IndexNow jika kategori cocok
      run: |
        changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^_posts/")
        for filepath in $changed; do
          # Ambil isi front matter YAML
          fm=$(awk '/^---/{y++} y==2{exit} {print}' "$filepath")
          # Cek apakah kategori cocok
          if echo "$fm" | grep -E "categories:.*(tutorial|bisnis|service|pelayanan|informasi)"; then
            filename=$(basename "$filepath" .md)
            year=$(echo "$filename" | cut -d'-' -f1)
            month=$(echo "$filename" | cut -d'-' -f2)
            day=$(echo "$filename" | cut -d'-' -f3)
            slug=$(echo "$filename" | cut -d'-' -f4-)
            url="https://adesansuniar.github.io/blog-adesansuniar/${year}/${month}/${day}/${slug}.html"
            echo "🔗 Submitting: $url"
            curl -s -X POST "https://www.bing.com/indexnow?url=$url&key=84bf3793852b4ee6966440bb4090ebe3"
          else
            echo "⏩ Lewati $filepath (kategori tidak sesuai)"
          fi
        done
